### ISSUE TITLE
[FEATURE] Display property and functions decorators

### ISSUE THREAD

**Issue by manekinekko** [compodoc/ts-stats#5]
- [x] properties
- [x] constructor args
- [x] methods

**Comment by dsherret** [comment]
Hey, this library will be awesome! I'm going to add `Node.forEachDescendant` in [#306](https://github.com/dsherret/ts-simple-ast/issues/306) in ts-simple-ast. That would make this whole library much easier/faster and would mean you could create a simple visitor to get all the decorators. Something like:

```ts
// Visitor.ts
export interface Visitor {
    visit(node: Node): void;
}

// DecoratorNameVisitor.ts
import { Node, TypeGuards } from "ts-simple-ast";
import { Visitor } from "./Visitor";

// obviously you'd want something better... just an example
export class DecoratorNameVisitor implements Visitor {
    private readonly names: string[] = [];

    visit(node: Node) {
        if (!TypeGuards.isDecorator(node))
            return;

        this.names.push(node.getFullName());
    }
    
    getDecoratorNames() {
        return [...this.names];
    }
}

// main.ts -- in some other file...
for (const sourceFile of sourceFiles) {
    sourceFile.forEachDescendant(descendant => {
        visitors.forEach(visitor => visitor.visit(descendant));
    });
}

console.log(decoratorNameVisitor.getNames());
```

**Comment by dsherret** [comment]
That `forEachDescendant` method now exists in 10.3.0.

**Comment by vogloblinsky** [comment]
Thanks @dsherret !

**Comment by manekinekko** [comment]
hi @dsherret I'm sorry I just saw your comment!
Actually I've managed to get all possible decorators with the previous API. Here is the current implementation: https://github.com/compodoc/ts-stats/blob/master/src/stats/decorators.ts#L17-L28

Will definetly look at the new API and plan a refactoring. Thanks a lot 😁

**Comment by dsherret** [comment]
Yeah, it would definitely be a performance boost to use `forEachDescendant`. It will reduce the number of passes over nodes in the AST.

By the way, do you want find decorators on classes nested in functions or namespaces?

```ts
namespace N {
    @Dec
    class C {}
}

function F {
    @Dec
    class C {
    }
}
```

The `.forEachDescendant` way will get those.

**Comment by manekinekko** [comment]
I like the `visitor` pattern better. this is actually what I've implemented in the `ngd` project: https://github.com/compodoc/ngd/blob/master/src/modules/compiler/src/compiler.ts#L153-L155

I'll refactor the `ts-stats::decorators` code asap to reflect that.

**Comment by manekinekko** [comment]
Alright, I just did the refactoring. It's much better. thank you 👍 
==> https://github.com/compodoc/ts-stats/blob/master/src/stats/decorators.ts#L8-L20

**Comment by vogloblinsky** [comment]
Asap === 1h for @manekinekko :smile:

**Comment by manekinekko** [comment]
Life is short ^^
